Repository Yejin0O0/shadcn-dialog-snippet, pull requests merged in 2024-11, with the labels that each got.

#40 feat: 다크 모드 추가
  index.html
  src/App.css
  src/App.tsx
  src/components/common/DialogCard.tsx
  src/components/common/Header.tsx
  src/components/common/Icons.tsx
  src/components/common/ModeToggle.tsx
  src/config/site.ts
  src/hooks/useMetaColor.ts
Labels: feat✨

#47 fix: Make a DialogDisplay and DialogToolBar
  src/App.tsx
  src/components/common/DialogDisplay.tsx
  src/components/common/DialogToolBar.tsx
Labels: feat✨

#49 feat: Add Category Tab
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/common/DialogNav.tsx
  src/components/common/Separator.tsx
  src/components/dialog/form/PaymentStepForm.tsx
  src/components/dialog/form/SignInForm.tsx
  src/components/dialog/form/SignUpForm.tsx
  src/components/ui/scroll-area.tsx
  src/layout/Header/Header.tsx
  src/layout/Header/ModeToggle.tsx
  src/layout/layout.tsx
  src/main.tsx
  src/page/HomePage/HomePage.tsx
  tailwind.config.js
Labels: design🖌️, feat✨

#54 feat: make a string version of dialog component
  src/components/common/DialogToolBar.tsx
  src/components/dialog/form/CheckBoxColumnForm/CheckBoxColumnFormBase.tsx
  src/components/dialog/form/CheckBoxColumnForm/checkBoxColumnFormString.ts
  src/components/dialog/form/CheckBoxRowForm/CheckBoxRowFormBase.tsx
  src/components/dialog/form/CheckBoxRowForm/checkBoxRowFormString.ts
  src/components/dialog/form/InnerScrollForm/InnerScrollFormBase.tsx
  src/components/dialog/form/InnerScrollForm/innerScrollFormString.ts
  src/components/dialog/form/PaymentStepForm/PaymentStepFormBase.tsx
  src/components/dialog/form/PaymentStepForm/paymentStepFormString.ts
  src/components/dialog/form/RadioBoxColumnForm/RadioBoxColumnFormBase.tsx
  src/components/dialog/form/RadioBoxColumnForm/radioBoxColumnFormString.ts
  src/components/dialog/form/RadioBoxRowForm/RadioBoxRowFormBase.tsx
  src/components/dialog/form/RadioBoxRowForm/radioBoxRowForm copy.ts
  src/components/dialog/form/SignIn/SignInFormBase.tsx
  src/components/dialog/form/SignIn/signInFormString.ts
  src/components/dialog/form/SignUp/SignUpFormBase.tsx
  src/components/dialog/form/SignUp/signUpFormString.tsx
  src/components/dialog/form/Survey/SurveyFormBase.tsx
  src/components/dialog/form/Survey/surveyFormString.ts
  src/components/dialog/information/InfoDialog/InfoDialogBase.tsx
  src/components/dialog/information/InfoDialog/infoDialogString.ts
  src/components/dialog/information/SuccessDialog/SuccessDialogBase.tsx
  src/components/dialog/information/SuccessDialog/successDialogString.ts
  src/components/dialog/information/UserProfileDialog/UserProfileDialogBase.tsx
  src/components/dialog/information/UserProfileDialog/userProfileDialogString.ts
  src/components/dialog/interrupt/Alert/ErrorAlert/ErrorAlertBase.tsx
  src/components/dialog/interrupt/Alert/ErrorAlert/errorAlertString.ts
  src/components/dialog/interrupt/Alert/WarningAlert/WarningAlertBase.tsx
  src/components/dialog/interrupt/Alert/WarningAlert/warningAlertString.ts
Labels: feat✨

#58 fix: add code props
  src/components/common/CodeSheet.tsx
  src/components/common/DialogDisplay.tsx
  src/components/common/DialogToolBar.tsx
  src/page/HomePage/HomePage.tsx
Labels: fix🛠️

#61 feat: Add Dialog Component on Drawel
  src/components/common/DialogDisplay.tsx
  src/components/common/DialogToolBar.tsx
Labels: refactor✍️
