Repository Yejin0O0/shadcn-dialog-snippet, pull requests merged in 2024-10, with the labels that each got.

#13 refactor: index.css shadcn 기본과 맞추기
  package-lock.json
  package.json
  src/components/mode-toggle.tsx
  src/components/theme-provider.tsx
  src/components/ui/dropdown-menu.tsx
  src/index.css
Labels: beforeLunch🍕, refactor✍️

#14 [feat] CheckBoxForm 컴포넌트 구현
  package-lock.json
  package.json
  src/components/examples/CheckBoxColumnForm.tsx
  src/components/examples/CheckBoxRowForm.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/form.tsx
Labels: 5PM🌝, feat✨

#19 feat: 상황별 alert dialog 생성
  src/App.tsx
  src/components/examples/alert/ErrorAlert.tsx
  src/components/examples/alert/InfoAlert.tsx
  src/components/examples/alert/SuccessAlert.tsx
  src/components/examples/alert/WarningAlert.tsx
Labels: 5PM🌝

#22 feat: 로그인 다이얼로그 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/examples/SignIn.tsx
Labels: feat✨

#34 [FEAT] 네비바 추가, 폴더 경로 수정
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/darkmode.svg
  src/assets/github.svg
  src/assets/logo.svg
  src/assets/twitter.svg
  src/components/Form/CheckBoxColumnForm.tsx
  src/components/Form/CheckBoxRowForm.tsx
  src/components/Form/InnerScrollForm.tsx
  src/components/Form/PaymentStepForm.tsx
  src/components/Form/RadioBoxColumnForm.tsx
  src/components/Form/RadioBoxRowForm.tsx
  src/components/Form/SignInForm.tsx
  src/components/Form/SignUpForm.tsx
  src/components/Form/SurveyForm.tsx
  src/components/Header/index.tsx
  src/components/Information/InfoDialog.tsx
  src/components/Information/SuccessDialog.tsx
  src/components/Information/UserProfileDialog.tsx
  src/components/Interrupt/Alert/ErrorAlert.tsx
  src/components/Interrupt/Alert/WarningAlert.tsx
  vite.config.ts
Labels: design🖌️, refactor✍️

#38 design: grid layout 적용
  src/App.tsx
Labels: beforeLunch🍕, design🖌️

#36 feat: 카드 제작
  src/App.tsx
  src/components/common/DialogCard.tsx
  src/components/common/Header.tsx
  src/components/common/ModeToggle.tsx
  src/components/dialog/form/CheckBoxColumnForm.tsx
  src/components/dialog/form/CheckBoxRowForm.tsx
  src/components/dialog/form/InnerScrollForm.tsx
  src/components/dialog/form/PaymentStepForm.tsx
  src/components/dialog/form/RadioBoxColumnForm.tsx
  src/components/dialog/form/RadioBoxRowForm.tsx
  src/components/dialog/form/SignInForm.tsx
  src/components/dialog/form/SignUpForm.tsx
  src/components/dialog/form/SurveyForm.tsx
  src/components/dialog/information/InfoDialog.tsx
  src/components/dialog/information/SuccessDialog.tsx
  src/components/dialog/information/UserProfileDialog.tsx
  src/components/dialog/interrupt/Alert/ErrorAlert.tsx
  src/components/dialog/interrupt/Alert/WarningAlert.tsx
  src/components/ui/card.tsx
  src/providers/ThemeProvider.tsx
Labels: beforeLunch🍕, design🖌️
