Repository Yejin0O0/shadcn-dialog-snippet, pull requests merged in 2025-01, with the labels that each got.

#73 chore: delete string .ts files
  src/__generated__/ErrorAlertBaseString.ts
  src/__generated__/InfoDialogBaseString.ts
  src/__generated__/SuccessDialogBaseString.ts
  src/__generated__/WarningAlertBaseString.ts
  src/components/dialog/form/CheckBoxColumnForm/checkBoxColumnFormString.ts
  src/components/dialog/form/InnerScrollForm/innerScrollFormString.ts
  src/components/dialog/form/OpenSatisfactionSurveyForm/openSatisfactionSurveyFormString.ts
  src/components/dialog/form/PaymentStepForm/paymentStepFormString.ts
  src/components/dialog/form/RadioBoxColumnForm/radioBoxColumnFormString.ts
  src/components/dialog/form/SignInForm/signInFormString.ts
  src/components/dialog/form/SignUpForm/signUpFormString.tsx
  src/components/dialog/index.tsx
  src/components/dialog/information/InfoDialog/infoDialogString.ts
  src/components/dialog/information/SuccessDialog/successDialogString.ts
  src/components/dialog/information/UserProfileDialog/userProfileDialogString.ts
  src/components/dialog/interrupt/Alert/ErrorAlert/errorAlertString.ts
  src/components/dialog/interrupt/Alert/WarningAlert/warningAlertString.ts
  src/page/HomePage/HomePage.tsx
Labels: chore🧹

#76 [refactor] Move Success, Info Dialog to Interrupt Category
  src/__generated__/CheckBoxRowFormBaseString.ts
  src/__generated__/InfoAlertBaseString.ts
  src/__generated__/RadioBoxRowFormBaseString.ts
  src/__generated__/SuccessAlertBaseString.ts
  src/components/dialog/index.tsx
  src/components/dialog/interrupt/ErrorAlert/ErrorAlert.tsx
  src/components/dialog/interrupt/ErrorAlert/ErrorAlertBase.tsx
  src/components/dialog/interrupt/InfoAlert/InfoAlert.tsx
  src/components/dialog/interrupt/InfoAlert/InfoAlertBase.tsx
  src/components/dialog/interrupt/SuccessAlert/SuccessAlert.tsx
  src/components/dialog/interrupt/SuccessAlert/SuccessAlertBase.tsx
  src/components/dialog/interrupt/WarningAlert/WarningAlert.tsx
  src/components/dialog/interrupt/WarningAlert/WarningAlertBase.tsx
  src/page/HomePage/HomePage.tsx
  src/scripts/convert-tsx-to-string.ts
Labels: refactor✍️

#81 [feat] Add Information Dialog - CreditsDialog
  package-lock.json
  package.json
  src/__generated__/CreditsDialogBaseString.ts
  src/components/dialog/index.tsx
  src/components/dialog/information/CreditsDialog/CreditsDialog.tsx
  src/components/dialog/information/CreditsDialog/CreditsDialogBase.tsx
  src/components/ui/accordion.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/layout/layout.tsx
  src/page/HomePage/HomePage.tsx
  tailwind.config.js
Labels: feat✨
